export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
//
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const SHOW_PROFILE = "SHOW_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
//
export const CREATE_QUESTION_ANSWERS = "CREATE_QUESTION_ANSWERS";
export const SHOW_QUESTION_ANSWERS = "SHOW_QUESTION_ANSWERS";
export const SHOW_QUESTION_AFTER_DELETE = "SHOW_QUESTION_AFTER_DELETE";
export const SHOW_SUBJECT = "SHOW_SUBJECT";
