-- MySQL Script generated by MySQL Workbench
-- Sun Sep 15 11:56:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema quizzz
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `quizzz` ;

-- -----------------------------------------------------
-- Schema quizzz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quizzz` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `quizzz` ;

-- -----------------------------------------------------
-- Table `quizzz`.`gamequestion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizzz`.`gamequestion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `quizzz`.`gamequestion` (
  `idGameTable` INT(11) NOT NULL,
  `idGameQuestion` INT(11) NOT NULL,
  PRIMARY KEY (`idGameTable`, `idGameQuestion`),
  INDEX `FK_GameQuestion_GameQuestion_GameChoices` (`idGameQuestion` ASC) VISIBLE,
  CONSTRAINT `FK_GameQuestion_GameQuestion_GameChoices`
    FOREIGN KEY (`idGameQuestion`)
    REFERENCES `quizzz`.`gamequestion_gamechoices` (`idGameQuestion`),
  CONSTRAINT `FK_GameQuestion_GameTable`
    FOREIGN KEY (`idGameTable`)
    REFERENCES `quizzz`.`gametable` (`idGameTable`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `quizzz`.`gamequestion_gamechoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizzz`.`gamequestion_gamechoices` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `quizzz`.`gamequestion_gamechoices` (
  `idGameQuestion` INT(11) NOT NULL,
  `gameQuestionName` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idGameQuestion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `quizzz`.`gamequestionchoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizzz`.`gamequestionchoices` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `quizzz`.`gamequestionchoices` (
  `idGameChoice` INT(11) NOT NULL,
  `idGameQuestion` INT(11) NOT NULL,
  `gameChoice` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `isRightChoice` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idGameChoice`, `idGameQuestion`),
  CONSTRAINT `FK_GameQuestionChoices_GameQuestion_GameChoices`
    FOREIGN KEY (`idGameChoice`)
    REFERENCES `quizzz`.`gamequestion_gamechoices` (`idGameQuestion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `quizzz`.`gametable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizzz`.`gametable` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `quizzz`.`gametable` (
  `idGameTable` INT(11) NOT NULL,
  `gameCode` MEDIUMINT(9) NULL DEFAULT NULL,
  `gameTitle` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `gameGradeBegin` CHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `gameGradeEnd` CHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `gameLevel` CHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `gamePlayed` INT(11) NULL DEFAULT NULL,
  `idSubject` INT(11) NULL DEFAULT NULL,
  `gameImage` LONGBLOB NULL DEFAULT NULL,
  `isPublic` TINYINT(1) NULL DEFAULT NULL,
  `gameTime` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idGameTable`),
  INDEX `FK_GameTable_QuizzzSubject` (`idSubject` ASC) VISIBLE,
  CONSTRAINT `FK_GameTable_QuizzzSubject`
    FOREIGN KEY (`idSubject`)
    REFERENCES `quizzz`.`quizzzsubject` (`idSubject`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `quizzz`.`quizzzsubject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizzz`.`quizzzsubject` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `quizzz`.`quizzzsubject` (
  `idSubject` INT(11) NOT NULL,
  `subjectName` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `subjectIcon` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idSubject`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `quizzz`.`sysdiagrams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizzz`.`sysdiagrams` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `quizzz`.`sysdiagrams` (
  `name` VARCHAR(160) NOT NULL,
  `principal_id` INT(11) NOT NULL,
  `diagram_id` INT(11) NOT NULL,
  `version` INT(11) NULL DEFAULT NULL,
  `definition` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`diagram_id`),
  UNIQUE INDEX `UK_principal_name` (`principal_id` ASC, `name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `quizzz`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizzz`.`user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `quizzz`.`user` (
  `idUser` INT(11) NOT NULL,
  `userFirstName` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `userLastName` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `userGrades` CHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `idSubject` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `FK_User_QuizzzSubject` (`idSubject` ASC) VISIBLE,
  CONSTRAINT `FK_User_QuizzzSubject`
    FOREIGN KEY (`idSubject`)
    REFERENCES `quizzz`.`quizzzsubject` (`idSubject`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `quizzz`.`userquestionanswer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quizzz`.`userquestionanswer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `quizzz`.`userquestionanswer` (
  `idUser` INT(11) NOT NULL,
  `idGameQuestion` INT(11) NOT NULL,
  `idGameChoice` INT(11) NULL DEFAULT NULL,
  `isRight` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`, `idGameQuestion`),
  INDEX `FK_UserQuestionAnswer_GameQuestion_GameChoices` (`idGameQuestion` ASC) VISIBLE,
  CONSTRAINT `FK_UserQuestionAnswer_GameQuestion_GameChoices`
    FOREIGN KEY (`idGameQuestion`)
    REFERENCES `quizzz`.`gamequestion_gamechoices` (`idGameQuestion`),
  CONSTRAINT `FK_UserQuestionAnswer_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `quizzz`.`user` (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
